# permissions for end users to view exports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: export-viewer-role
rules:
- apiGroups:
  - mirror.openshift.io
  resources:
  - exports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirror.openshift.io
  resources:
  - exports/status
  verbs:
  - get
