# permissions for end users to view imports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: import-viewer-role
rules:
- apiGroups:
  - mirror.openshift.io
  resources:
  - imports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirror.openshift.io
  resources:
  - imports/status
  verbs:
  - get
