apiVersion: mirror.openshift.io/v1alpha1
kind: Export
metadata:
  name: export-sample-8
spec:
  providerType: AWS
  storageObject: s3://rcook-mirror
  pvcSize: 100
  credSecret: aws-creds
  imageSetConfiguration: imageset
  dockerConfigSecret: pull-secret
