apiVersion: mirror.openshift.io/v1alpha1
kind: Import
metadata:
  name: reggie
spec:
  providerType: AWS
  storageObject: s3://rcook-mirror 
  pvcSize: 100
  credSecret: aws-creds
  certificateSecret: certs
